### PR TITLE
Fixes for 0.10

### PR DESCRIPTION
**Pull request by roymacdonald**
Hi @bakercp,
hope you're doing great!
I made some fixes so this superb addon can work on the current OF master.
best!

### CODE REVIEW

**Comment by bakercp** [comment]
Thanks!  Please check to see if my merged changes still work for you ...

**Comment by roymacdonald** [comment]
Great.
Although I get  a runtime error.
If the cache path doesn't exist (the folder structure) the app crashes at https://github.com/bakercp/ofxSQLiteCpp/blob/master/libs/SQLiteCpp/src/Database.cpp#L86
printing out this
```
SQLite::Exception SQLITE_CANTOPEN  
libc++abi.dylib: terminating with uncaught exception of type SQLite::Exception: unable to open database file
```
It is supposed to create the file if it doesn't exist but it doesn't create the folder structure if missing. I can fix it easily with `ofFile::exists()` but you might have a better solution.
BTW, I also had this problem with what I PR'd.

**Comment by bakercp** [comment]
I've got a fix for that over in ofxSQLiteCpp -- I'll push fixes there.

**Comment by roymacdonald** [comment]
That would be great! thanks once again for your great addons! :)

**Pull request merged**
